# These are supported funding model platforms
PIX: 52.933.745/0001-07 # Replace with your username
custom: ['https://www.paypal.com/paypalme/nydcompany', 'https://pago.pagopar.com/1pnm4'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
